INSERT INTO `dw-2205-team4_lostdimension`.`product_dim`
(`Product_SK`,
`Product_ID(NK)`,
`Product_Description`,
`Price1`,
`Price2`,
`Unit_Cost`,
`ProductType_ID`,
`ProductType_Description`,
`BUID`,
`Business_Name`,
`Business_Unit_Abbreviation`,
`Supplier_Name`,
`Supplier_Address`,
`Supplier_State`,
`Supplier_Zip`,
`Product_Division`)
SELECT `product_dim`.`Product_SK`,
    `product_dim`.`Product_ID(NK)`,
    `product_dim`.`Product_Description`,
    `product_dim`.`Price1`,
    `product_dim`.`Price2`,
    `product_dim`.`Unit_Cost`,
    `product_dim`.`ProductType_ID`,
    `product_dim`.`ProductType_Description`,
    `product_dim`.`BUID`,
    `product_dim`.`Business_Name`,
    `product_dim`.`Business_Unit_Abbreviation`,
    `product_dim`.`Supplier_Name`,
    `product_dim`.`Supplier_Address`,
    `product_dim`.`Supplier_State`,
    `product_dim`.`Supplier_Zip`,
    `product_dim`.`Product_Division`
FROM `dw-2205-team4_salesorders`.`product_dim`;